### ISSUE TITLE
Show the error

### ISSUE THREAD

**Issue by vielhuber** [micromata/cli-error-notifier#12]
Hello!

I first had the problem that every error caused my onchange script to break and exit. I had to rerun npm run build every time.

Then I discovered cli-error-notifier but now I have the problem that I don't see the error messages anymore (they are not printed in the console anymore).

How do you guys work with this on your daily basis without even seeing the actual error messages?

**Comment by mischah** [comment]
Hej @vielhuber,

I see the original message in the Terminal like when using this package like described in the readme:

*package.json snippet:*
```
{
  "scripts": {
    "eslint": "eslint src",
    "eslint:fix": "npm run eslint --silent -- --fix",
    "eslint:watch": "onchange \"src/**/*.js\" -- onerror \"npm run eslint --silent\""
  }
}
```

It would be helpful if you could provide the content of your package.json to make it possible to have a look at what’s happening in your use case.

**Comment by mischah** [comment]
Thanks for the detailed information.
Hope to find time in the next couple of days to dig into this.

One additional question: Which Node version are you using?

**Comment by mageshravi** [comment]
I use node v8.12.0.
I may have some additional info. If the task emitting the error is nested deep inside, the error is suppressed.
My function call is something like this,
```
# error from task D suppressed
mytask -> onerror 'task A' -> task B -> task C -> task D

npm run mytask
```

I could see the error in terminal when I changed it to this
```
mytask -> task A -> task B -> task C -> onerror 'task D'

npm run mytask
```

**Comment by vielhuber** [comment]
My node version is 9.4.0.
Same behaviour here.

**Comment by mischah** [comment]
Fixed in the latest version.
