### ISSUE TITLE
npm audit

### ISSUE THREAD

**Issue by vielhuber** [micromata/cli-error-notifier#33]
Hello!

I've got 2 high vulnerabilities when running `npm audit`.

Can you please update the dependencies?

Or could you provide an alternative to this nice project?

**Comment by vielhuber** [comment]
Any update on this?

**Comment by mischah** [comment]
@vielhuber 
Done 🎉

![image](https://user-images.githubusercontent.com/441011/190357009-21f0c591-4698-43e6-9560-32ae539d2bb5.png)


See https://github.com/micromata/cli-error-notifier/releases
